name: dpm-flow
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - abseil-cpp=20230802.0=h6a678d5_2
  - absl-py=2.1.0=py312h06a4308_0
  - aiohttp=3.9.5=py312h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - attrs=23.1.0=py312h06a4308_0
  - blas=1.0=mkl
  - blinker=1.6.2=py312h06a4308_0
  - brotli-python=1.0.9=py312h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.7.2=h06a4308_0
  - cachetools=5.3.3=py312h06a4308_0
  - certifi=2024.7.4=py312h06a4308_0
  - cffi=1.16.0=py312h5eee18b_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py312h06a4308_0
  - cryptography=42.0.5=py312hdda0065_1
  - expat=2.6.2=h6a678d5_0
  - frozenlist=1.4.0=py312h5eee18b_0
  - google-auth=2.29.0=py312h06a4308_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpc-cpp=1.48.2=he1ff14a_4
  - grpcio=1.48.2=py312he1ff14a_4
  - gtest=1.14.0=hdb19cb5_1
  - h5py=3.11.0=py312h34c39bb_0
  - hdf5=1.12.1=h2b7332f_3
  - idna=3.7=py312h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - joblib=1.4.2=py312h06a4308_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libcurl=8.7.1=h251f7ec_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnghttp2=1.57.0=h2d74bed_0
  - libprotobuf=3.20.3=he621ea3_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - markdown=3.4.1=py312h06a4308_0
  - markupsafe=2.1.3=py312h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.8=py312h5eee18b_0
  - mkl_random=1.2.4=py312hdb19cb5_0
  - multidict=6.0.4=py312h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - numpy=1.26.4=py312hc5e2394_0
  - numpy-base=1.26.4=py312h0da6c21_0
  - oauthlib=3.2.2=py312h06a4308_0
  - openssl=3.0.14=h5eee18b_0
  - pip=24.0=py312h06a4308_0
  - protobuf=3.20.3=py312h6a678d5_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.8.0=py312h06a4308_0
  - pyopenssl=24.0.0=py312h06a4308_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.4=h5148396_1
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.2=py312h06a4308_0
  - requests-oauthlib=2.0.0=py312h06a4308_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-learn=1.4.2=py312h526ad5a_1
  - scipy=1.13.1=py312hc5e2394_0
  - setuptools=69.5.1=py312h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.6.0=py_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - threadpoolctl=3.5.0=py312he106c6f_0
  - tk=8.6.14=h39e8969_0
  - tqdm=4.66.4=py312he106c6f_0
  - tzdata=2024a=h04d1e81_0
  - urllib3=2.2.2=py312h06a4308_0
  - werkzeug=3.0.3=py312h06a4308_0
  - wheel=0.43.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yarl=1.9.3=py312h5eee18b_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - contourpy==1.2.1
    - cycler==0.12.1
    - cython==3.0.10
    - docker-pycreds==0.4.0
    - filelock==3.13.1
    - fonttools==4.53.1
    - fsspec==2024.2.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - jinja2==3.1.3
    - kiwisolver==1.4.5
    - matplotlib==3.9.1
    - mpmath==1.3.0
    - networkx==3.2.1
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cuda-cupti-cu11==11.8.87
    - nvidia-cuda-nvrtc-cu11==11.8.89
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cudnn-cu11==8.7.0.84
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.3.0.86
    - nvidia-cusolver-cu11==11.4.1.48
    - nvidia-cusparse-cu11==11.7.5.86
    - nvidia-nccl-cu11==2.20.5
    - nvidia-nvtx-cu11==11.8.86
    - packaging==24.1
    - pillow==10.2.0
    - platformdirs==4.2.2
    - psutil==6.0.0
    - pyparsing==3.1.2
    - pyrvo2==0.0.0
    - pyrvo23d==0.1.0
    - python-dateutil==2.9.0.post0
    - pyyaml==6.0.1
    - sentry-sdk==2.9.0
    - setproctitle==1.3.3
    - smmap==5.0.1
    - sympy==1.12
    - torch==2.3.1+cu118
    - torchaudio==2.3.1+cu118
    - torchvision==0.18.1+cu118
    - typing-extensions==4.9.0
    - wandb==0.17.4
    - zuko==1.2.0
prefix: /home/cplou/anaconda3/envs/dpm-flow
